name: SSHTESTS
on: [push]
jobs:
  SSHTESTS:
    runs-on: self-hosted
    strategy:
      fail-fast: false
    steps:
    - name: Configure SSH
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa      
        chmod 600 ~/.ssh/id_rsa
        cat $HOME/.ssh/known_hosts
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Check dir
      run: |
        vboxmanage -v
        vagrant -v
        ls helpers/
