name: SSHTESTS
on: [push]
jobs:
  SSHTESTS:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-latest]
    steps:
    - name: Configure SSH
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa      
        chmod 600 ~/.ssh/id_rsa
    - uses: actions/checkout@v1
      with:
        submodules: recursive
